name: Felix
favicon: null
layout_spectrum: 0.1450629
typography_spectrum: 0.3154921
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Felix Hofmann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020201'
    - '#AB9A80'
    - '#FFFFFF'
    - '#6C4321'
    - '#5D6E76'
  brandStrength: 0.5489362
  lightness: 0.3924067
  saturation: 0.744156
  rhythmicContrast: 0.4994757
purpose: []
